name: Handle calculate request from issue
on: 
  issues:
    types:
      - opened

jobs:
  handler:
    runs-on: ubuntu-latest
    outputs:
      player_id: ${{ steps.request-handler.outputs.player_id }}
      if_std: ${{ steps.request-handler.outputs.if_std }}
      if_taiko: ${{ steps.request-handler.outputs.if_taiko }}
      if_catch: ${{ steps.request-handler.outputs.if_catch }}
      if_mania: ${{ steps.request-handler.outputs.if_mania }}
    steps:
      - name: Test if need to calculate
        if: contains( ${{ github.event.issue.title }}, '[Calculate Request]' )
        id: request-handler
        uses: actions/github-script@v7
        with:
          script: |
            const issue_input = JSON.parse(`${{ github.event.issue.body }}`)
            core.setOutput("player_id", issue_input.player_id )
            core.setOutput("if_std", issue_input.calculate_std )
            core.setOutput("if_taiko", issue_input.calculate_taiko )
            core.setOutput("if_catch", issue_input.calculate_catch )
            core.setOutput("if_mania", issue_input.calculate_mania )
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, @${{ github.actor }}

                Your request has been handled, you can get your result here: 
                ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
            })

  calculator:
    needs: handler
    runs-on: ubuntu-latest
    steps:
      - name: Check if player id is valid
        uses: actions/github-script@v7
        with:
          script: |
            const playerId = "${{needs.handler.outputs.player_id}}"
            if (!playerId.match(/^[A-Za-z0-9 \[\]_-]+$/)) {
              core.setFailed(`${{needs.handler.outputs.player_id}} is an invalid player id!`)
            }

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Fetch osu-tools
        run: git clone --recurse-submodules https://github.com/ppy/osu-tools

      - name: Pre-build
        run: dotnet run --project "./osu-tools/PerformanceCalculator" -- profile --help

      - name: Calculate std pp
        if: ${{ needs.handler.outputs.if_std == 'true' && success()}}
        run: dotnet run --project "./osu-tools/PerformanceCalculator" -- profile --ruleset 0 "${{needs.handler.outputs.player_id}}" ${{secrets.CLIENT_ID}} ${{secrets.CLIENT_TOKEN}} | tee "${{needs.handler.outputs.player_id}}-std.txt"

      - name: Clean and get std brief result
        if: ${{ needs.handler.outputs.if_std == 'true' && success()}}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const path = './${{needs.handler.outputs.player_id}}-std.txt'
            const lines = fs.readFileSync(path, 'utf-8').split('\n')
            const userIndex = lines.findIndex(line => line.startsWith('User:'))
            if (userIndex === -1) {
              throw new Error('Wrong output file: Missing User keywords')
            }
            const relevantContent = lines.slice(userIndex)
            fs.writeFileSync(path, relevantContent.join('\n'), 'utf-8')
            const outputLine = ['Mode:     std', ...relevantContent.slice(0, 3)]
            core.notice(outputLine.join(' | '))

      - name: Calculate taiko pp
        if: ${{ needs.handler.outputs.if_taiko == 'true' && success()}}
        run: dotnet run --project "./osu-tools/PerformanceCalculator" -- profile --ruleset 1 "${{needs.handler.outputs.player_id}}" ${{secrets.CLIENT_ID}} ${{secrets.CLIENT_TOKEN}} | tee "${{needs.handler.outputs.player_id}}-taiko.txt"

      - name: Clean and get taiko brief result
        if: ${{ needs.handler.outputs.if_taiko == 'true' && success()}}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const path = './${{needs.handler.outputs.player_id}}-taiko.txt'
            const lines = fs.readFileSync(path, 'utf-8').split('\n')
            const userIndex = lines.findIndex(line => line.startsWith('User:'))
            if (userIndex === -1) {
              throw new Error('Wrong output file: Missing User keywords')
            }
            const relevantContent = lines.slice(userIndex)
            fs.writeFileSync(path, relevantContent.join('\n'), 'utf-8')
            const outputLine = ['Mode:     std', ...relevantContent.slice(0, 3)]
            core.notice(outputLine.join(' | '))

      - name: Calculate catch pp
        if: ${{ needs.handler.outputs.if_catch == 'true' && success()}}
        run: dotnet run --project "./osu-tools/PerformanceCalculator" -- profile --ruleset 2 "${{needs.handler.outputs.player_id}}" ${{secrets.CLIENT_ID}} ${{secrets.CLIENT_TOKEN}} | tee "${{needs.handler.outputs.player_id}}-catch.txt"

      - name: Clean and get catch brief result
        if: ${{ needs.handler.outputs.if_catch == 'true' && success()}}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const path = './${{needs.handler.outputs.player_id}}-catch.txt'
            const lines = fs.readFileSync(path, 'utf-8').split('\n')
            const userIndex = lines.findIndex(line => line.startsWith('User:'))
            if (userIndex === -1) {
              throw new Error('Wrong output file: Missing User keywords')
            }
            const relevantContent = lines.slice(userIndex)
            fs.writeFileSync(path, relevantContent.join('\n'), 'utf-8')
            const outputLine = ['Mode:     std', ...relevantContent.slice(0, 3)]
            core.notice(outputLine.join(' | '))

      - name: Calculate mania pp
        if: ${{ needs.handler.outputs.if_mania == 'true' && success()}}
        run: dotnet run --project "./osu-tools/PerformanceCalculator" -- profile --ruleset 3 "${{needs.handler.outputs.player_id}}" ${{secrets.CLIENT_ID}} ${{secrets.CLIENT_TOKEN}} | tee "${{needs.handler.outputs.player_id}}-mania.txt"

      - name: Clean and get mania brief result
        if: ${{ needs.handler.outputs.if_mania == 'true' && success()}}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const path = './${{needs.handler.outputs.player_id}}-mania.txt'
            const lines = fs.readFileSync(path, 'utf-8').split('\n')
            const userIndex = lines.findIndex(line => line.startsWith('User:'))
            if (userIndex === -1) {
              throw new Error('Wrong output file: Missing User keywords')
            }
            const relevantContent = lines.slice(userIndex)
            fs.writeFileSync(path, relevantContent.join('\n'), 'utf-8')
            const outputLine = ['Mode:     std', ...relevantContent.slice(0, 3)]
            core.notice(outputLine.join(' | '))

      - name: Get current date
        run: echo "RUN_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}

      - name: Upload detailed result
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{needs.handler.outputs.player_id}}-profile-${{env.RUN_DATE}}
          path: ./*.txt
      
      - name: Close current issue
        if: success()
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Workflow run has done!
            See result here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Auto-closing this issue.

      - name: Close current issue
        if: failure()
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Workflow run encounters failure!
            See result here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Please report this if you need to seek help.
            Auto-closing this issue.